In [1]:
# install 
!pip install numpy

Unable to create process using 'C:\Users\Akshem Dhami\anaconda3\python.exe "C:\Users\Akshem Dhami\anaconda3\Scripts\pip-script.py" install numpy'


In [2]:
import numpy as np

In [176]:
# difference b/w list and numpy array
num = [10,20,30,50]
num + 10

TypeError: can only concatenate list (not "int") to list

In [3]:
num = [10,20,30,50]
[ i + 10   for i in num]

[20, 30, 40, 60]

In [4]:
ar1 = np.array(num)
ar1

array([10, 20, 30, 50])

In [5]:
print(ar1)

[10 20 30 50]


In [6]:
ar1 + 10

array([20, 30, 40, 60])

In [7]:
# 
num = [10,20,"a","b"]
num

[10, 20, 'a', 'b']

In [8]:
type(num[0])

int

In [9]:
type(num[-1])

str

In [10]:
ar1 = np.array(num)
ar1

array(['10', '20', 'a', 'b'], dtype='<U11')

In [11]:
np.array([10,20.0,30, "python"])

array(['10', '20.0', '30', 'python'], dtype='<U32')

In [12]:
# 3. Numpy is faster than list

import time
start_time = time.time()
[ ((i**2) + 10)/2   for i in range(0,100000)]
end_time = time.time()
print("time taken", end_time - start_time)

time taken 0.057776689529418945


In [13]:
# 3. Numpy is faster than list
import time
import numpy as np
ar1 = np.array(range(0,100000))
start_time = time.time()
((ar1**2)+10)/2
end_time = time.time()
print("time taken", end_time - start_time)

time taken 0.002040386199951172


In [14]:
ar1 = np.array([10,20.0,30, "python"])
ar1

array(['10', '20.0', '30', 'python'], dtype='<U32')

In [15]:
type(ar1)

numpy.ndarray

In [16]:
num = list(ar1)
type(num[0])

numpy.str_

In [17]:
# list is 1 dimensional
# numpy array can be n-dimensional

In [18]:
listolist = [  [10,20,30],  [1,2,3],   [11,12,13] ]
listolist

[[10, 20, 30], [1, 2, 3], [11, 12, 13]]

In [19]:
np.array(listolist)

array([[10, 20, 30],
       [ 1,  2,  3],
       [11, 12, 13]])

In [20]:
listolist = [  [ [10,20],[30, 40]],  [[1,2],[3,4]],   [[11,12],[13,14]] ]
np.array(listolist)

array([[[10, 20],
        [30, 40]],

       [[ 1,  2],
        [ 3,  4]],

       [[11, 12],
        [13, 14]]])

In [21]:
import numpy as np
listo =  [10,20,30]
ar1d = np.array(listo)
ar1d

array([10, 20, 30])

In [187]:
# attributes of arrays
len(ar1d)

3

In [23]:
ar1d.size

3

In [24]:
ar1d.shape

(3,)

In [25]:
ar1d.dtype

dtype('int32')

In [26]:
type(ar1d)

numpy.ndarray

In [27]:
listolist = [  [10,20,30],  [1,2,3],   [11,12,13], [34,35,36] ]
ar2d = np.array(listolist)
ar2d

array([[10, 20, 30],
       [ 1,  2,  3],
       [11, 12, 13],
       [34, 35, 36]])

In [28]:
len(ar2d)

4

In [29]:
ar2d.size

12

In [30]:
r,c = ar2d.shape
r

4

In [31]:
c

3

In [32]:
listolist = [  [ [10,20],[30, 40]],  [[1,2],[3,4]],   [[11,12],[13,14]] ]
ar3d = np.array(listolist)
ar3d

array([[[10, 20],
        [30, 40]],

       [[ 1,  2],
        [ 3,  4]],

       [[11, 12],
        [13, 14]]])

In [33]:
len(ar3d)

3

In [34]:
ar3d.size

12

In [35]:
ar3d.shape

(3, 2, 2)

In [36]:
ar3d.dtype

dtype('int32')

In [37]:
ar1d.ndim

1

In [38]:
ar2d.ndim

2

In [39]:
ar3d.ndim

3

In [40]:
# different ways of creating arrays using numpy functions

In [41]:
# range(2.1,10, 1)

In [42]:
np.arange(2.1,10, 0.5)

array([2.1, 2.6, 3.1, 3.6, 4.1, 4.6, 5.1, 5.6, 6.1, 6.6, 7.1, 7.6, 8.1,
       8.6, 9.1, 9.6])

In [178]:
arr = np.arange(0,10, 0.5)
arr.shape

(20,)

In [179]:
arr.size

20

In [180]:
arr.reshape(1,20)

array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
        6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]])

In [181]:
arr.reshape(20,1)

array([[0. ],
       [0.5],
       [1. ],
       [1.5],
       [2. ],
       [2.5],
       [3. ],
       [3.5],
       [4. ],
       [4.5],
       [5. ],
       [5.5],
       [6. ],
       [6.5],
       [7. ],
       [7.5],
       [8. ],
       [8.5],
       [9. ],
       [9.5]])

In [182]:
arr.reshape(2,10)

array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]])

In [183]:
arr.reshape(4,5)

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [184]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [49]:
np.zeros(4)

array([0., 0., 0., 0.])

In [50]:
np.zeros( (2,4)  )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.ones( 4  , dtype = "str")

array(['1', '1', '1', '1'], dtype='<U1')

In [52]:
np.ones( (4 , 2) )

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [53]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.random.randint(10)

3

In [55]:
np.random.randint(low = 10, high = 20)

11

In [56]:
np.random.randint(low = 10, high = 20, size = 5)

array([15, 15, 17, 15, 13])

In [57]:
np.random.seed(200)
np.random.randint(low = 10, high = 20, size = 5)

array([19, 10, 14, 17, 19])

In [58]:
np.random.seed(200)
np.random.randint(low = 10, high = 20, size = 5)

array([19, 10, 14, 17, 19])

In [191]:
# indexing and slicing on 2d array
n = [[10,20,30],[1,2,3], [101,102,103]]
arr = np.array(n)
print(arr)

[[ 10  20  30]
 [  1   2   3]
 [101 102 103]]


In [60]:
Aarr[0]

array([10, 20, 30])

In [61]:
arr[-1]

array([101, 102, 103])

In [62]:
arr[ 0 : 2]  # same dim

array([[10, 20, 30],
       [ 1,  2,  3]])

In [63]:
arr[0][0]

10

In [64]:
arr[-1][1]

102

In [65]:
arr[ : :2]

array([[ 10,  20,  30],
       [101, 102, 103]])

In [66]:
# arr[row   , col]
arr

array([[ 10,  20,  30],
       [  1,   2,   3],
       [101, 102, 103]])

In [67]:
arr[0,0]

10

In [68]:
arr[1,1]

2

In [69]:
arr[0,2]

30

In [70]:
# slicing
arr[ 0 : 2   , 0 : 2   ]

array([[10, 20],
       [ 1,  2]])

In [71]:
arr

array([[ 10,  20,  30],
       [  1,   2,   3],
       [101, 102, 103]])

In [72]:
# slicing
arr[ :    , 0 : 2   ]

array([[ 10,  20],
       [  1,   2],
       [101, 102]])

In [73]:
# slicing
arr[ :    , : : 2  ]

array([[ 10,  30],
       [  1,   3],
       [101, 103]])

In [192]:
arr

array([[ 10,  20,  30],
       [  1,   2,   3],
       [101, 102, 103]])

In [196]:
arr[ :  :   , : :   ]

array([[ 10,  20,  30],
       [  1,   2,   3],
       [101, 102, 103]])

In [76]:
arr[ :   ,    [0,-1]    ]

array([[ 10,  30],
       [  1,   3],
       [101, 103]])

In [77]:
arr[ :   ,    [0,-1, 0]    ]

array([[ 10,  30,  10],
       [  1,   3,   1],
       [101, 103, 101]])

In [78]:
arr[ [-1,0,-1,1] ,    : ]

array([[101, 102, 103],
       [ 10,  20,  30],
       [101, 102, 103],
       [  1,   2,   3]])

In [79]:
arr

array([[ 10,  20,  30],
       [  1,   2,   3],
       [101, 102, 103]])

In [80]:
arr[ [-1,0,-1,1] ,    0 : 2 ]

array([[101, 102],
       [ 10,  20],
       [101, 102],
       [  1,   2]])

In [81]:
arr

array([[ 10,  20,  30],
       [  1,   2,   3],
       [101, 102, 103]])

In [198]:
arr[ [-1,0] ,   [0,1]]

array([101,  20])

In [208]:
arr[  [1,2,0]  , [0,2,2]  ]

# A10
# A22
# A02

array([  1, 103,  30])

In [84]:
np.random.seed(200)
arr = np.random.randint(low = 10, high = 100, size = 25).reshape(5,5)
arr

array([[36, 26, 78, 52, 65],
       [86, 89, 99, 24, 67],
       [99, 21, 16, 52, 66],
       [11, 17, 61, 37, 83],
       [25, 11, 33, 95, 34]])

In [85]:
# display the first 3 rows
# display the first 3 columns
# display the alternate rows
# display aletrnate columns
# display the alternate rows and alternate columns
# display  rows index(2 to 4) , cols index(1 to 3)
# display the alternate rows and last 3 columns

# fetch 86, 66, 24, 83
# fetch 0th,2nd and last rows ,all the columns

In [86]:
# display the first 3 rows
arr[ : 3]

array([[36, 26, 78, 52, 65],
       [86, 89, 99, 24, 67],
       [99, 21, 16, 52, 66]])

In [87]:
# display the first 3 columns
arr[ :  , : 3]

array([[36, 26, 78],
       [86, 89, 99],
       [99, 21, 16],
       [11, 17, 61],
       [25, 11, 33]])

In [88]:
# display the alternate rows
arr[ : :2]

array([[36, 26, 78, 52, 65],
       [99, 21, 16, 52, 66],
       [25, 11, 33, 95, 34]])

In [89]:
# display the alternate cols
arr[ : , : :2]

array([[36, 78, 65],
       [86, 99, 67],
       [99, 16, 66],
       [11, 61, 83],
       [25, 33, 34]])

In [90]:
arr[ : :2, : :2]

array([[36, 78, 65],
       [99, 16, 66],
       [25, 33, 34]])

In [91]:
# display  rows index)(2 to 4 , cols index(1 to 3)
arr[ 2 : 5,   1 : 4]

array([[21, 16, 52],
       [17, 61, 37],
       [11, 33, 95]])

In [92]:
# display the alternate rows and last 3 columns

arr[ : :2,   -3 : ]

array([[78, 52, 65],
       [16, 52, 66],
       [33, 95, 34]])

In [93]:
# fetch 86, 66, 24, 83

In [94]:
arr

array([[36, 26, 78, 52, 65],
       [86, 89, 99, 24, 67],
       [99, 21, 16, 52, 66],
       [11, 17, 61, 37, 83],
       [25, 11, 33, 95, 34]])

In [95]:
# 86 - A10
# 66 - A24
# 24 - A13
# 83 - A34
arr [ [1,2,1,3],  [0,4,3,4] ]

array([86, 66, 24, 83])

In [96]:
# fetch 0th,2nd and last rows ,all the columns
arr[  [0,2,4], : ]

array([[36, 26, 78, 52, 65],
       [99, 21, 16, 52, 66],
       [25, 11, 33, 95, 34]])

In [97]:
arr

array([[36, 26, 78, 52, 65],
       [86, 89, 99, 24, 67],
       [99, 21, 16, 52, 66],
       [11, 17, 61, 37, 83],
       [25, 11, 33, 95, 34]])

In [98]:
arr[ : :-1]

array([[25, 11, 33, 95, 34],
       [11, 17, 61, 37, 83],
       [99, 21, 16, 52, 66],
       [86, 89, 99, 24, 67],
       [36, 26, 78, 52, 65]])

In [99]:
arr[ :   , : :-1]

array([[65, 52, 78, 26, 36],
       [67, 24, 99, 89, 86],
       [66, 52, 16, 21, 99],
       [83, 37, 61, 17, 11],
       [34, 95, 33, 11, 25]])

In [100]:
arr[ : :-1 , : :-1 ]

array([[34, 95, 33, 11, 25],
       [83, 37, 61, 17, 11],
       [66, 52, 16, 21, 99],
       [67, 24, 99, 89, 86],
       [65, 52, 78, 26, 36]])

In [101]:
# indexing

In [209]:
arr = np.array([[1,0,2],[ 2,4,5]])
arr
# [[1,2]
# [0,4]
# [2,5]]

array([[1, 0, 2],
       [2, 4, 5]])

In [210]:
arr.transpose()

array([[1, 2],
       [0, 4],
       [2, 5]])

In [211]:
ar3d

array([[[10, 20],
        [30, 40]],

       [[ 1,  2],
        [ 3,  4]],

       [[11, 12],
        [13, 14]]])

In [105]:
ar3d[0,0,0]

10

In [106]:
ar3d[0 : 2, 0 : 1 , 0 : 1]

array([[[10]],

       [[ 1]]])

In [212]:
ar1d

array([10, 20, 30])

In [107]:
# Performing arithmatic operations on arrays
# +, -, *, /,//,%,**
ar1d  + 10

array([20, 30, 40])

In [108]:
ar1d  * 2

array([20, 40, 60])

In [109]:
ar2d  + 10

array([[20, 30, 40],
       [11, 12, 13],
       [21, 22, 23],
       [44, 45, 46]])

In [110]:
ar3d + 10

array([[[20, 30],
        [40, 50]],

       [[11, 12],
        [13, 14]],

       [[21, 22],
        [23, 24]]])

In [111]:
ar1d + np.array([2,4,5])

array([12, 24, 35])

In [175]:
ar1d + np.array([2,4,5,9])

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [213]:
ar2d2 = np.array([[1,2,3], [1,2,3],[1,2,3],[1,2,3]])
ar2d2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [113]:
ar2d + ar2d2

array([[11, 22, 33],
       [ 2,  4,  6],
       [12, 14, 16],
       [35, 37, 39]])

In [114]:
ar2d * ar2d2

array([[ 10,  40,  90],
       [  1,   4,   9],
       [ 11,  24,  39],
       [ 34,  70, 108]])

In [214]:
newAr = np.array([1,2,3])
newAr

array([1, 2, 3])

In [116]:
ar2d

array([[10, 20, 30],
       [ 1,  2,  3],
       [11, 12, 13],
       [34, 35, 36]])

In [117]:
ar2d + newAr

array([[11, 22, 33],
       [ 2,  4,  6],
       [12, 14, 16],
       [35, 37, 39]])

In [118]:
ar2d.shape

(4, 3)

In [119]:
newAr.shape

(3,)

In [120]:
ar2d

array([[10, 20, 30],
       [ 1,  2,  3],
       [11, 12, 13],
       [34, 35, 36]])

In [121]:
newAr

array([1, 2, 3])

In [122]:
import numpy as np
np.random.seed(1)
arr2d =np.random.randint(low=1 , high= 12, size = 12).reshape(4,3)
arr2d

array([[ 6,  9, 10],
       [ 6,  1,  1],
       [ 2,  8,  7],
       [10,  3,  5]])

In [123]:
arr2d * newAr

array([[ 6, 18, 30],
       [ 6,  2,  3],
       [ 2, 16, 21],
       [10,  6, 15]])

In [124]:
newAr

array([1, 2, 3])

In [125]:
ar2d

array([[10, 20, 30],
       [ 1,  2,  3],
       [11, 12, 13],
       [34, 35, 36]])

In [126]:
ar2d.shape

(4, 3)

In [127]:
newAr.shape

(3,)

In [128]:
ar2d.dot(newAr.reshape(3,1))

array([[140],
       [ 14],
       [ 74],
       [212]])

In [129]:
# comparison operators
# >, <, >=, <= , !=, ==
np.random.seed(200)
arr = np.random.randint(low = 10, 
                        high = 100, 
                        size = 25).reshape(5,5)
arr

array([[36, 26, 78, 52, 65],
       [86, 89, 99, 24, 67],
       [99, 21, 16, 52, 66],
       [11, 17, 61, 37, 83],
       [25, 11, 33, 95, 34]])

In [130]:
arr > 18

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [131]:
arr [arr > 18]

array([36, 26, 78, 52, 65, 86, 89, 99, 24, 67, 99, 21, 52, 66, 61, 37, 83,
       25, 33, 95, 34])

In [132]:
arr [arr < 18]

array([16, 11, 17, 11])

In [133]:
np.where(arr < 18)

(array([2, 3, 3, 4], dtype=int64), array([2, 0, 1, 1], dtype=int64))

In [134]:
np.where(arr < 18,  "<18" , ">=18")

array([['>=18', '>=18', '>=18', '>=18', '>=18'],
       ['>=18', '>=18', '>=18', '>=18', '>=18'],
       ['>=18', '>=18', '<18', '>=18', '>=18'],
       ['<18', '<18', '>=18', '>=18', '>=18'],
       ['>=18', '<18', '>=18', '>=18', '>=18']], dtype='<U4')

In [135]:
np.where(arr < 18, "<18", ">=18")

array([['>=18', '>=18', '>=18', '>=18', '>=18'],
       ['>=18', '>=18', '>=18', '>=18', '>=18'],
       ['>=18', '>=18', '<18', '>=18', '>=18'],
       ['<18', '<18', '>=18', '>=18', '>=18'],
       ['>=18', '<18', '>=18', '>=18', '>=18']], dtype='<U4')

In [136]:
import numpy as np

A1 = np.array([1,2,5,10])
A1

array([ 1,  2,  5, 10])

In [137]:
np.sum(A1)

18

In [138]:
np.min(A1)

1

In [139]:
np.max(A1)

10

In [140]:
np.mean(A1)

4.5

In [141]:
np.std(A1)

3.5

In [142]:
np.var(A1)

12.25

In [143]:
np.power(A1,2)

array([  1,   4,  25, 100], dtype=int32)

In [144]:
np.sqrt(A1)

array([1.        , 1.41421356, 2.23606798, 3.16227766])

In [145]:
np.log(A1)

array([0.        , 0.69314718, 1.60943791, 2.30258509])

In [146]:
# comparison operators
# >, <, >=, <= , !=, ==
np.random.seed(200)
arr = np.random.randint(low = 10, 
                        high = 100, 
                        size = 25).reshape(5,5)
arr

array([[36, 26, 78, 52, 65],
       [86, 89, 99, 24, 67],
       [99, 21, 16, 52, 66],
       [11, 17, 61, 37, 83],
       [25, 11, 33, 95, 34]])

In [147]:
np.min(arr)

11

In [148]:
np.max(arr)

99

In [149]:
np.sum(arr)

1283

In [150]:
36+ 26 + 78 + 52 + 65

257

In [151]:
np.sum(arr, axis=0)

array([257, 164, 287, 260, 315])

In [152]:
86+ 89+ 99+ 24+ 67

365

In [153]:
sum((99, 21, 16, 52, 66))

254

In [154]:
sum((36,
86,
99,
11,
25))

257

In [155]:
sum((26,
89,
21,
17,
11))

164

In [156]:
arr

array([[36, 26, 78, 52, 65],
       [86, 89, 99, 24, 67],
       [99, 21, 16, 52, 66],
       [11, 17, 61, 37, 83],
       [25, 11, 33, 95, 34]])

In [157]:
np.sum(arr,axis=0)

array([257, 164, 287, 260, 315])

In [158]:
sum(arr[ :  , 0])

257

In [159]:
sum(arr[ :  , 1])

164

In [160]:
sum(arr[ :  , 2])

287

In [161]:
sum(arr[ :  , 3])

260

In [162]:
sum(arr[ :  , 4])

315

In [163]:
np.sum(arr,axis=1)

array([257, 365, 254, 209, 198])

In [164]:
sum(arr[ 0   ,   :  ])

257

In [165]:
sum(arr[ 1   ,   :  ])

365

In [166]:
sum(arr[ 2   ,   :  ])

254

In [167]:
sum(arr[ 3  ,   :  ])

209

In [168]:
sum(arr[ 4  ,   :  ])

198

In [169]:
# [ [10,12,18],
#   [ 2, 5, 9]]

In [170]:
# find rows and cols sum

In [171]:
newarr = np.array([ [10,12,18],
          [ 2, 5, 9]])
newarr

array([[10, 12, 18],
       [ 2,  5,  9]])

In [172]:
np.sum(newarr, axis= 1)

array([40, 16])

In [173]:
np.sum(newarr, axis= 0)

array([12, 17, 27])

In [219]:
a=np.sum((0.0), initial = 2)
a

2.0

In [218]:
newarr

array([[10, 12, 18],
       [ 2,  5,  9]])