In [1]:
import numpy as np
np.random.seed(5)
a=np.random.randint(low=5, high=100, size=10)
a1=a.reshape(2,5)
a2=a.reshape(5,2)
a3=a1.reshape(5,2)
print('a1: 2 rows, 5 columns:','\n', a1, '\n')
print('a2: 5 columns, 2 rows:', '\n', a2, '\n')
print('a3: 5 columns, 2 rows:', '\n', a3)

a1: 2 rows, 5 columns: 
 [[83 66 21 78 13]
 [67 32 35 85 12]] 

a2: 5 columns, 2 rows: 
 [[83 66]
 [21 78]
 [13 67]
 [32 35]
 [85 12]] 

a3: 5 columns, 2 rows: 
 [[83 66]
 [21 78]
 [13 67]
 [32 35]
 [85 12]]


In [2]:
import numpy as np

np.random.seed(0)
arr = np.random.randint(low = 10, high=100, size = 9)
arr1 = arr.reshape(3,3)
arr1

array([[54, 57, 74],
       [77, 77, 19],
       [93, 31, 46]])

In [3]:
np.random.seed(300)
arr1d = np.random.randint(low = 10, high=100, size = 9)
arr2d = arr1d.reshape(3,3)
arr2d

array([[91, 31, 84],
       [19, 95, 32],
       [51, 86, 70]])

In [4]:
arr

array([54, 57, 74, 77, 77, 19, 93, 31, 46])

In [5]:
arr1d

array([91, 31, 84, 19, 95, 32, 51, 86, 70])

In [6]:
np.concatenate(   ( arr,arr1d ) )

array([54, 57, 74, 77, 77, 19, 93, 31, 46, 91, 31, 84, 19, 95, 32, 51, 86,
       70])

In [7]:
arr1

array([[54, 57, 74],
       [77, 77, 19],
       [93, 31, 46]])

In [8]:
arr2d

array([[91, 31, 84],
       [19, 95, 32],
       [51, 86, 70]])

In [9]:
np.concatenate(  (arr1, arr2d) )

array([[54, 57, 74],
       [77, 77, 19],
       [93, 31, 46],
       [91, 31, 84],
       [19, 95, 32],
       [51, 86, 70]])

In [10]:
np.concatenate(  (arr1, arr2d) ,axis=1)

array([[54, 57, 74, 91, 31, 84],
       [77, 77, 19, 19, 95, 32],
       [93, 31, 46, 51, 86, 70]])

In [11]:
newarr = arr2d[  : , 0 ]
newarr

array([91, 19, 51])

In [12]:
arr2d

array([[91, 31, 84],
       [19, 95, 32],
       [51, 86, 70]])

In [13]:
np.concatenate(  (arr2d, newarr) , axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [16]:
newarr = arr2d[  : , 0 ]
newarr

array([91, 19, 51])

In [17]:
newarr = arr2d[  : , 0 : 1 ]
newarr

array([[91],
       [19],
       [51]])

In [19]:
newarr = arr2d[:,0:0]
newarr

array([], shape=(3, 0), dtype=int32)

In [19]:
np.concatenate(  (arr2d, newarr) , axis=1)

array([[91, 31, 84, 91],
       [19, 95, 32, 19],
       [51, 86, 70, 51]])

In [20]:
arr2d.shape

(3, 3)

In [21]:
newarr.shape

(3, 1)

In [22]:
np.concatenate(  (arr2d, newarr) , axis=1)

array([[91, 31, 84, 91],
       [19, 95, 32, 19],
       [51, 86, 70, 51]])

In [24]:
n = arr2d[0:1, : ]
print(n.shape)
print(n)

(1, 3)
[[91 31 84]]


In [25]:
arr2d.shape

(3, 3)

In [26]:
np.concatenate(  (arr2d, n) , axis=0)

array([[91, 31, 84],
       [19, 95, 32],
       [51, 86, 70],
       [91, 31, 84]])

In [27]:
arr

array([54, 57, 74, 77, 77, 19, 93, 31, 46])

In [28]:
arr1d

array([91, 31, 84, 19, 95, 32, 51, 86, 70])

In [39]:
np.stack( (arr,arr1d))

array([[54, 57, 74, 77, 77, 19, 93, 31, 46],
       [91, 31, 84, 19, 95, 32, 51, 86, 70]])

In [32]:
np.stack( (arr,arr1d), axis=1)

array([[54, 91],
       [57, 31],
       [74, 84],
       [77, 19],
       [77, 95],
       [19, 32],
       [93, 51],
       [31, 86],
       [46, 70]])

In [33]:
arr1

array([[54, 57, 74],
       [77, 77, 19],
       [93, 31, 46]])

In [34]:
arr2d

array([[91, 31, 84],
       [19, 95, 32],
       [51, 86, 70]])

In [35]:
np.stack(  (arr1,arr2d) )  

array([[[54, 57, 74],
        [77, 77, 19],
        [93, 31, 46]],

       [[91, 31, 84],
        [19, 95, 32],
        [51, 86, 70]]])

In [36]:
np.stack(  (arr1,arr2d), axis=1 )

array([[[54, 57, 74],
        [91, 31, 84]],

       [[77, 77, 19],
        [19, 95, 32]],

       [[93, 31, 46],
        [51, 86, 70]]])

In [40]:
np.random.seed(0)
ArrA = np.random.randint(low = 10, high=100, size = 20)
ArrA = ArrA.reshape(4,5)
ArrA

array([[54, 57, 74, 77, 77],
       [19, 93, 31, 46, 97],
       [80, 98, 98, 22, 68],
       [75, 49, 97, 56, 98]])

In [42]:
arr

array([54, 57, 74, 77, 77, 19, 93, 31, 46])

In [46]:
b = arr[ : 8]
b

array([54, 57, 74, 77, 77, 19, 93, 31])

In [47]:
np.split(b, 4 )

[array([54, 57]), array([74, 77]), array([77, 19]), array([93, 31])]

In [48]:
arr

array([54, 57, 74, 77, 77, 19, 93, 31, 46])

In [49]:
np.split(arr, 2 )

ValueError: array split does not result in an equal division

In [55]:
np.split(arr,[2, 6])

[array([54, 57]), array([74, 77, 77, 19]), array([93, 31, 46])]

In [56]:
ArrA

array([[54, 57, 74, 77, 77],
       [19, 93, 31, 46, 97],
       [80, 98, 98, 22, 68],
       [75, 49, 97, 56, 98]])

In [57]:
np.split(ArrA, 2)

[array([[54, 57, 74, 77, 77],
        [19, 93, 31, 46, 97]]),
 array([[80, 98, 98, 22, 68],
        [75, 49, 97, 56, 98]])]

In [63]:
np.split(ArrA, 2, axis=1)

ValueError: array split does not result in an equal division

In [62]:
np.split(ArrA, 1, axis=1)

[array([[54, 57, 74, 77, 77],
        [19, 93, 31, 46, 97],
        [80, 98, 98, 22, 68],
        [75, 49, 97, 56, 98]])]

In [61]:
np.split(ArrA, 5, axis=1)

[array([[54],
        [19],
        [80],
        [75]]),
 array([[57],
        [93],
        [98],
        [49]]),
 array([[74],
        [31],
        [98],
        [97]]),
 array([[77],
        [46],
        [22],
        [56]]),
 array([[77],
        [97],
        [68],
        [98]])]

In [64]:
ArrA

array([[54, 57, 74, 77, 77],
       [19, 93, 31, 46, 97],
       [80, 98, 98, 22, 68],
       [75, 49, 97, 56, 98]])

In [77]:
np.split(ArrA, [2,3], axis=0)

[array([[54, 57, 74, 77, 77],
        [19, 93, 31, 46, 97]]),
 array([[80, 98, 98, 22, 68]]),
 array([[75, 49, 97, 56, 98]])]

In [78]:
np.split(ArrA, [2,3], axis=1)

[array([[54, 57],
        [19, 93],
        [80, 98],
        [75, 49]]),
 array([[74],
        [31],
        [98],
        [97]]),
 array([[77, 77],
        [46, 97],
        [22, 68],
        [56, 98]])]

In [79]:
import numpy as np
np.random.seed(0)
Arr = np.random.randint(low = 10, high=100, size = 20)
ArrA = Arr.reshape(4,5)
ArrA

array([[54, 57, 74, 77, 77],
       [19, 93, 31, 46, 97],
       [80, 98, 98, 22, 68],
       [75, 49, 97, 56, 98]])

In [80]:
Arr

array([54, 57, 74, 77, 77, 19, 93, 31, 46, 97, 80, 98, 98, 22, 68, 75, 49,
       97, 56, 98])

In [81]:
for i in Arr:
    print(i)

54
57
74
77
77
19
93
31
46
97
80
98
98
22
68
75
49
97
56
98


In [84]:
for i in ArrA:
    for j in i:
        print(j)

54
57
74
77
77
19
93
31
46
97
80
98
98
22
68
75
49
97
56
98


In [85]:
for i in np.nditer(ArrA):
    print(i)

54
57
74
77
77
19
93
31
46
97
80
98
98
22
68
75
49
97
56
98


In [86]:
ArrA[0,0] = 100
ArrA

array([[100,  57,  74,  77,  77],
       [ 19,  93,  31,  46,  97],
       [ 80,  98,  98,  22,  68],
       [ 75,  49,  97,  56,  98]])

In [2]:
import pandas as pd
ages = [12,24,18,92]
ages

[12, 24, 18, 92]

In [3]:
import pandas as pd
ages = [12,24,18,92]
pd.Series(ages)

0    12
1    24
2    18
3    92
dtype: int64

In [8]:
ages1 = [12,24,18,92]
pd.Series(ages, index = ["A","B","C", "D"] )

A    12
B    24
C    18
D    92
dtype: int64

In [9]:
ages2 = [12,24,18,92]
pd.Series(ages, index = [101, 102, 103, 104] )

101    12
102    24
103    18
104    92
dtype: int64

In [10]:
ages3 = (12,24,18,92)
pd.Series(ages, index = [101, 102, 103, 104] )

101    12
102    24
103    18
104    92
dtype: int64

In [20]:
type(ages)

tuple

In [17]:
import numpy as np
age4 = np.array([12,24,18,92])
pd.Series(age4, index = ["A","B","C", "D"] )

A    12
B    24
C    18
D    92
dtype: int32

In [93]:
ages = {"A" : 12, "B" : 24, "C" : 18, "D" : 92}
s = pd.Series(ages )
s

A    12
B    24
C    18
D    92
dtype: int64

In [94]:
s["C"]

18

In [95]:
ages = [12,24,18,92]
s1 = pd.Series(ages )
s1

0    12
1    24
2    18
3    92
dtype: int64

In [96]:
s1[2]

18

In [97]:
ages = [12,24,18,92]
s1 = pd.Series(ages, index = ["M" ,"M","F", "F"] )
s1

M    12
M    24
F    18
F    92
dtype: int64

In [98]:
s1["F"]

F    18
F    92
dtype: int64

In [99]:
s1.index

Index(['M', 'M', 'F', 'F'], dtype='object')

In [100]:
s.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [101]:
s1.values

array([12, 24, 18, 92], dtype=int64)

In [102]:
ages = [12,24,18,92]
s1 = pd.Series(ages )
s1

0    12
1    24
2    18
3    92
dtype: int64

In [103]:
s1[0 : 2]

0    12
1    24
dtype: int64

In [104]:
s["A" : "C" : 2]

A    12
C    18
dtype: int64

In [105]:
s > 20

A    False
B     True
C    False
D     True
dtype: bool

In [106]:
s[s > 20]

B    24
D    92
dtype: int64

In [107]:
ages = [12,24,18,92]
s1 = pd.Series(ages, index = ["A","B","A","C"] )
s1

A    12
B    24
A    18
C    92
dtype: int64

In [108]:
s1["A" : "A"]

KeyError: "Cannot get left slice bound for non-unique label: 'A'"

In [109]:
s1[0 : 3]  

A    12
B    24
A    18
dtype: int64

In [110]:
ages

[12, 24, 18, 92]

In [111]:
ages = (12,24,18,92)
s2 = pd.Series(ages, index = [101, 102, 103, 104] )
s2

101    12
102    24
103    18
104    92
dtype: int64

In [112]:
s2[102]

24

In [113]:
s2[101  : 103]  # loc, iloc

Series([], dtype: int64)

In [114]:
s + 2

A    14
B    26
C    20
D    94
dtype: int64

In [ ]:
# DataFrames

In [22]:
stud_data = [["S101", 45, "BLR"],
            ["S102", 32, "CHN"]]
pd.DataFrame(stud_data, index = ["A","B"])

0   1    2
A  S101  45  BLR
B  S102  32  CHN

In [116]:
stud_data = [  ["S101", 45, "BLR"],
            ["S102", 32, "CHN"]]
pd.DataFrame(stud_data, 
             columns = ["SID","Marks","City"] )

SID  Marks City
0  S101     45  BLR
1  S102     32  CHN

In [117]:
stud_data = np.random.randint(10,100, 25).reshape(5,5)
pd.DataFrame(stud_data, 
             columns = ["col1", "col2","col3","col4","col5"])

col1  col2  col3  col4  col5
0    91    47    35    87    82
1    19    30    90    79    89
2    57    74    92    98    59
3    39    29    29    24    49
4    42    75    19    67    42

In [23]:
d = {"SID"    :   ["S101","S102","S103","S104"],
    "Marks" : [32,45,18,22],
    "city" : ["BLR","CHN","MUM","CHN"]}
pd.DataFrame(d, index=['1','2','3','4'])

SID  Marks city
1  S101     32  BLR
2  S102     45  CHN
3  S103     18  MUM
4  S104     22  CHN

In [119]:
d = {"SID"    :   ["S101","S102","S103","S104"],
    "Marks" : [32,45,18, 22],
    "city" : ["BLR","CHN","MUM","CHN"]}
df = pd.DataFrame(d)
df

SID  Marks city
0  S101     32  BLR
1  S102     45  CHN
2  S103     18  MUM
3  S104     22  CHN

In [120]:
df.to_csv("stud_data.csv")

In [25]:
d = {"S@ID"    :   ["S101","S102","S103","S104"],
    "Marks" : (32,45,18, 22),
    "city" : ["BLR","CHN","MUM","CHN"],
    "course" : "DSE"}
df = pd.DataFrame(d)
df

S@ID  Marks city course
0  S101     32  BLR    DSE
1  S102     45  CHN    DSE
2  S103     18  MUM    DSE
3  S104     22  CHN    DSE

In [26]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [27]:
df.values

array([['S101', 32, 'BLR', 'DSE'],
       ['S102', 45, 'CHN', 'DSE'],
       ['S103', 18, 'MUM', 'DSE'],
       ['S104', 22, 'CHN', 'DSE']], dtype=object)

In [30]:
df.set_index("SID", inplace=True)

KeyError: "None of ['SID'] are in the columns"

In [31]:
df.reset_index(inplace=True)

In [32]:
df

S@ID  Marks city course
0  S101     32  BLR    DSE
1  S102     45  CHN    DSE
2  S103     18  MUM    DSE
3  S104     22  CHN    DSE

In [38]:
# fetching cols and rows
df.S@ID

AttributeError: 'DataFrame' object has no attribute 'S'

In [39]:
df["S@ID"]

0    S101
1    S102
2    S103
3    S104
Name: S@ID, dtype: object

In [40]:
df[   ["course","S@ID"]   ]

course  S@ID
0    DSE  S101
1    DSE  S102
2    DSE  S103
3    DSE  S104

In [50]:
df[0]

KeyError: 0

In [51]:
df[0 : 2]  # loc, iloc

S@ID  Marks city course
0  S101     32  BLR    DSE
1  S102     45  CHN    DSE

In [52]:
# iloc - integer based default labels
#   0   1   2
# 0
# 1
# 2

In [53]:
df.iloc[0] #0 row

S@ID      S101
Marks       32
city       BLR
course     DSE
Name: 0, dtype: object

In [54]:
df.iloc[ : , 0] #all rows 0 column

0    S101
1    S102
2    S103
3    S104
Name: S@ID, dtype: object

In [55]:
df.iloc[0 : 3 ]

S@ID  Marks city course
0  S101     32  BLR    DSE
1  S102     45  CHN    DSE
2  S103     18  MUM    DSE

In [56]:
df.iloc[0 : 3,  0 : 2 ]

S@ID  Marks
0  S101     32
1  S102     45
2  S103     18

In [57]:
df.iloc[0 : 3 : 2,  0 : 2 ]

S@ID  Marks
0  S101     32
2  S103     18

In [60]:
df.iloc[0, 1]

35

In [61]:
df.iloc[0, 1] = 38
df

S@ID  Marks city course
0  S101     38  BLR    DSE
1  S102     45  CHN    DSE
2  S103     18  MUM    DSE
3  S104     22  CHN    DSE

In [59]:
df.iloc[ [1,3,0,0]]

S@ID  Marks city course
1  S102     45  CHN    DSE
3  S104     22  CHN    DSE
0  S101     35  BLR    DSE
0  S101     35  BLR    DSE

In [62]:
df.iloc[ : , [0, -1]]

S@ID course
0  S101    DSE
1  S102    DSE
2  S103    DSE
3  S104    DSE

In [63]:
df.loc[ 0 :2]  # end is inclusive

S@ID  Marks city course
0  S101     38  BLR    DSE
1  S102     45  CHN    DSE
2  S103     18  MUM    DSE

In [64]:
df.loc[ 0 :2, "S@ID" : "Marks"]  # end is inclusive

S@ID  Marks
0  S101     38
1  S102     45
2  S103     18

In [65]:
df.loc[ 0 :2, ["S@ID","city"]]  # end is inclusive

S@ID city
0  S101  BLR
1  S102  CHN
2  S103  MUM

In [66]:
# filtering data
df[df["Marks"]  > 40]

S@ID  Marks city course
1  S102     45  CHN    DSE

In [67]:
df[df["Marks"]  > 40] ["S@ID"]

1    S102
Name: S@ID, dtype: object

In [68]:
df[df["Marks"]  > 40] [[ "S@ID", "Marks"]]

S@ID  Marks
1  S102     45

In [69]:
df

S@ID  Marks city course
0  S101     38  BLR    DSE
1  S102     45  CHN    DSE
2  S103     18  MUM    DSE
3  S104     22  CHN    DSE

In [70]:
df[df["Marks"] > 30]

S@ID  Marks city course
0  S101     38  BLR    DSE
1  S102     45  CHN    DSE

In [71]:
df[df["city"] == "BLR"]

S@ID  Marks city course
0  S101     38  BLR    DSE

In [72]:
df[   (df["Marks"] > 30 ) &   (df["city"] == "BLR")]

S@ID  Marks city course
0  S101     38  BLR    DSE

In [73]:
df[   (df["Marks"] > 30 ) |   (df["city"] == "BLR")]

S@ID  Marks city course
0  S101     38  BLR    DSE
1  S102     45  CHN    DSE

In [74]:
df[~(df["Marks"] > 30 )]

S@ID  Marks city course
2  S103     18  MUM    DSE
3  S104     22  CHN    DSE

In [75]:
df.columns

Index(['S@ID', 'Marks', 'city', 'course'], dtype='object')

In [76]:
df["Marks"] + 2

0    40
1    47
2    20
3    24
Name: Marks, dtype: int64

In [77]:
df["Marks"] =  df["Marks"] + 2
df

S@ID  Marks city course
0  S101     40  BLR    DSE
1  S102     47  CHN    DSE
2  S103     20  MUM    DSE
3  S104     24  CHN    DSE

In [78]:
d["Age"] = 20
d

{'S@ID': ['S101', 'S102', 'S103', 'S104'],
 'Marks': (32, 45, 18, 22),
 'city': ['BLR', 'CHN', 'MUM', 'CHN'],
 'course': 'DSE',
 'Age': 20}

In [80]:
df["age"] = [20,22,26,21]
df

S@ID  Marks city course  age
0  S101     40  BLR    DSE   20
1  S102     47  CHN    DSE   22
2  S103     20  MUM    DSE   26
3  S104     24  CHN    DSE   21

In [81]:
df.drop(columns = "age", inplace=True)

In [82]:
df

S@ID  Marks city course
0  S101     40  BLR    DSE
1  S102     47  CHN    DSE
2  S103     20  MUM    DSE
3  S104     24  CHN    DSE

In [83]:
data = {"Description" : ["Iphone-14-65000", 
                         "Iphone-13-56000"]}
data = pd.DataFrame(data)
data

Description
0  Iphone-14-65000
1  Iphone-13-56000

In [84]:
data["Description"].str.split("-")

0    [Iphone, 14, 65000]
1    [Iphone, 13, 56000]
Name: Description, dtype: object

In [85]:
"Iphone-14-65000".split("-")

['Iphone', '14', '65000']

In [86]:
data["Description"].str.split("-", expand=True)

0   1      2
0  Iphone  14  65000
1  Iphone  13  56000

In [87]:
data = {"Description" : ["Iphone-14-128-65000", 
                         "Iphone-13-56000"]}
data = pd.DataFrame(data)
data["Description"].str.split("-")

0    [Iphone, 14, 128, 65000]
1         [Iphone, 13, 56000]
Name: Description, dtype: object

In [88]:
data["Description"].str.split("-", expand=True)

0   1      2      3
0  Iphone  14    128  65000
1  Iphone  13  56000   None